version: 2
jobs:
  build:
    docker:
      - image: golang
    working_directory: /go/src/github.com/raviqqe/muffet
    steps:
      - checkout

      - run:
          name: Setup
          command: |
            apt -y update --fix-missing
            apt -y upgrade
            apt -y install rake

      - run:
          name: Dependencies
          command: rake deps

      - run:
          name: Lint
          command: rake lint

      - run:
          name: Build
          command: rake build

      - run:
          name: Unit Test
          command: rake unit_test

      - run:
          name: Coverage Report
          command: |
            bash <(curl -s https://codecov.io/bash)

      - run:
          name: Integration Test
          command: |
            rake serve
            sleep 1
            rake integration_test

      - setup_remote_docker

      - run:
          name: Docker Image
          command: |
            if [ $CIRCLE_BRANCH = master ]
            then
              curl -L https://download.docker.com/linux/static/stable/x86_64/docker-17.12.1-ce.tgz |
              tar -xz -C /tmp
              mv /tmp/docker/* /usr/bin

              docker build -t raviqqe/muffet .
              docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
              docker push raviqqe/muffet
              version=$(./muffet --version)
              docker tag raviqqe/muffet raviqqe/muffet:$version
              docker push raviqqe/muffet:$version
            fi
