version: 2
workflows:
  version: 2
  all:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
      - docker:
          requires:
            - build
          filters:
            branches:
              only: master
jobs:
  build:
    docker:
      - image: golang
    environment:
      CGO_ENABLED: "0"
      GO111MODULE: "on"
    working_directory: /go/src/github.com/raviqqe/muffet
    steps:
      - checkout
      - run: tools/dependencies.sh
      - run: tools/lint.sh
      - run: tools/build.sh
      - run: tools/unit_test.sh
      - run: tools/integration_test.sh
      - persist_to_workspace:
          root: .
          paths:
            - muffet
  release:
    docker:
      - image: golang
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: |
          version=$(./muffet --version)

          if git tag -l | grep $version
          then
            exit 0
          fi

          git tag $version
          git push --tags
          curl -sL https://git.io/goreleaser | bash
  docker:
    docker:
      - image: docker:17
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: .
      - run: |
          name=$DOCKER_USER/muffet
          version=$(./muffet --version)

          if [ $version == $(docker run $name --version) ]
          then
            exit 0
          fi

          docker build -t $name .
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker push $name
          docker tag $name $name:$version
          docker push $name:$version
